import { Injectable } from '@nestjs/common';
import { Pool, PoolClient } from 'pg';
import { createHash } from 'crypto';

@Injectable()
export class TruthLogService {
  constructor(private readonly pool: Pool) {}

  /**
   * Appends an event to the cryptographically linked tamper-evident log.
   */
  async appendEvent(eventType: string, payload: Record<string, any>): Promise<string> {
    const client: PoolClient = await this.pool.connect();

    try {
      await client.query('BEGIN');

      // 1. Fetch the latest hash (using FOR UPDATE to prevent race conditions during insertion)
      //    If the table is empty, use a genesis hash.
      const latestLogQuery = `
        SELECT current_hash 
        FROM event_log 
        ORDER BY created_at DESC 
        LIMIT 1 
        FOR UPDATE;
      `;
      const latestRes = await client.query(latestLogQuery);
      
      const previousHash = latestRes.rows.length > 0 ? latestRes.rows[0].current_hash : 'GENESIS_HASH';

      // 2. Compute the new hash
      const payloadString = JSON.stringify(payload);
      // We do not include the physical DB timestamp in the hash input because it is generated by default NOW() on insert, 
      // making it impossible to pre-compute exactly. We hash the previous hash + payload.
      const hashInput = `${previousHash}${payloadString}`;
      const currentHash = createHash('sha256').update(hashInput).digest('hex');

      // 3. Insert the new log entry
      const insertQuery = `
        INSERT INTO event_log (event_type, payload, previous_hash, current_hash)
        VALUES ($1, $2, $3, $4)
        RETURNING id;
      `;
      const insertRes = await client.query(insertQuery, [
        eventType,
        payload,
        previousHash,
        currentHash
      ]);

      await client.query('COMMIT');
      return insertRes.rows[0].id;
    } catch (e) {
      await client.query('ROLLBACK');
      throw e;
    } finally {
      client.release();
    }
  }
}
