#!/usr/bin/env npx tsx
/**
 * build-chat-context.ts
 *
 * Reads key source files and assembles them into a static knowledge base
 * exported from src/web/lib/styx-knowledge.ts. No vector DB needed —
 * the assembled content fits within Llama 3.3 70B's 128K context window.
 *
 * Usage: npx tsx scripts/build-chat-context.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "..");

interface SourceFile {
  label: string;
  path: string;
  /** If set, only include lines 1..maxLines */
  maxLines?: number;
}

const SOURCES: SourceFile[] = [
  { label: "PROJECT OVERVIEW (CLAUDE.md)", path: "CLAUDE.md" },
  {
    label: "BEHAVIORAL LOGIC (oath categories, constants, streams)",
    path: "src/shared/libs/behavioral-logic.ts",
  },
  {
    label: "INTEGRITY SCORE (algorithm, tiers, Fury accuracy)",
    path: "src/shared/libs/integrity.ts",
  },
  { label: "MONEY UTILITIES", path: "src/shared/libs/money.ts" },
  { label: "DATABASE SCHEMA", path: "src/api/database/schema.sql" },
  {
    label: "FEATURE BACKLOG (executive summary + P0/P1)",
    path: "docs/FEATURE-BACKLOG.md",
    maxLines: 80,
  },
  {
    label: "IMPLEMENTATION STATUS (claim-to-control matrix)",
    path: "docs/planning/planning--implementation-status.md",
  },
  {
    label: "PHASE 1 PRIVATE BETA SCOPE",
    path: "docs/planning/planning--phase1-private-beta-scope.md",
  },
  { label: "PROJECT METADATA (seed.yaml)", path: "seed.yaml" },
];

function readSource(src: SourceFile): string {
  const fullPath = resolve(ROOT, src.path);
  let content: string;
  try {
    content = readFileSync(fullPath, "utf-8");
  } catch {
    console.warn(`WARNING: Could not read ${src.path}, skipping.`);
    return "";
  }

  if (src.maxLines) {
    content = content.split("\n").slice(0, src.maxLines).join("\n");
  }

  return content;
}

function buildKnowledge(): string {
  const sections = SOURCES.map((src) => {
    const content = readSource(src);
    if (!content) return "";
    return `=== ${src.label} ===\nFile: ${src.path}\n\n${content}`;
  }).filter(Boolean);

  return sections.join("\n\n");
}

function main() {
  console.log("Building Styx chat knowledge base...");

  const knowledge = buildKnowledge();
  const outPath = resolve(ROOT, "src/web/lib/styx-knowledge.ts");

  // Ensure directory exists
  mkdirSync(dirname(outPath), { recursive: true });

  // Escape backticks and ${} in the content for template literal safety
  const escaped = knowledge
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  const output = `// AUTO-GENERATED by scripts/build-chat-context.ts — do not edit manually.
// Regenerate with: npx tsx scripts/build-chat-context.ts

export const STYX_KNOWLEDGE = \`${escaped}\`;
`;

  writeFileSync(outPath, output, "utf-8");

  const sizeKB = (Buffer.byteLength(knowledge, "utf-8") / 1024).toFixed(1);
  const approxTokens = Math.round(Buffer.byteLength(knowledge, "utf-8") / 3.5);
  console.log(`Written to: ${outPath}`);
  console.log(`Knowledge size: ${sizeKB} KB (~${approxTokens} tokens)`);
}

main();
